modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="rubble_ray"
version="${file.jarVersion}"
displayName="Rubble Ray Mod"
logoFile = "logo.png"

description='''

'''
[[dependencies.rubble_ray]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rubble_ray]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
